{{- if .Values.webui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cronjob-scale-down-operator.fullname" . }}-webui
  labels:
    {{- include "cronjob-scale-down-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: webui
spec:
  type: {{ .Values.webui.service.type }}
  ports:
    - port: {{ .Values.webui.service.port }}
      targetPort: 8082
      protocol: TCP
      name: webui
  selector:
    {{- include "cronjob-scale-down-operator.selectorLabels" . | nindent 4 }}
{{- end }}
