# Default test values for chart testing
nameOverride: "test-cronjob-operator"

image:
  repository: cronschedules/z4ck404/cronjob-scale-down-operator
  tag: "0.3.0"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  limits:
    memory: "256Mi"
    cpu: "200m"
  requests:
    memory: "128Mi"
    cpu: "100m"

# Web UI configuration
webUI:
  enabled: true
  service:
    type: ClusterIP
    port: 8082

# Service account
serviceAccount:
  create: true
  automount: true

# Security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Pod annotations
podAnnotations:
  kubectl.kubernetes.io/default-container: manager
