# High availability configuration test values
nameOverride: "ha-cronjob-operator"

image:
  repository: ghcr.io/cronschedules/cronjob-scale-down-operator
  tag: "0.4.0"
  pullPolicy: IfNotPresent

# Multiple replicas for HA testing
replicaCount: 2

resources:
  limits:
    memory: "512Mi"
    cpu: "500m"
  requests:
    memory: "256Mi"
    cpu: "250m"

# Web UI configuration
webUI:
  enabled: true
  service:
    type: ClusterIP
    port: 8082

# Service account
serviceAccount:
  create: true
  automount: true

# Security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532

# Pod disruption budget for HA
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Anti-affinity for HA
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - cronjob-scale-down-operator
          topologyKey: kubernetes.io/hostname
