# Minimal configuration test values
nameOverride: "minimal-cronjob-operator"

image:
  repository: ghcr.io/cronschedules/cronjob-scale-down-operator
  tag: "0.4.0"
  pullPolicy: IfNotPresent

replicaCount: 1

# Minimal resources
resources:
  limits:
    memory: "128Mi"
    cpu: "100m"
  requests:
    memory: "64Mi"
    cpu: "50m"

# Disable Web UI for minimal test
webUI:
  enabled: false

# Service account
serviceAccount:
  create: true
  automount: true

# Security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532
