# Test values for chart testing in CI
nameOverride: "test-cronjob-operator"

image:
  repository: cronschedules/z4ck404/cronjob-scale-down-operator
  tag: "0.3.0"
  pullPolicy: Always

replicaCount: 1

# Reduced resources for testing
resources:
  limits:
    memory: "64Mi"
    cpu: "50m"
  requests:
    memory: "16Mi"
    cpu: "5m"

# Disable Web UI for testing to reduce resource usage
webUI:
  enabled: false

# Service account
serviceAccount:
  create: true
  automount: true

# Security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Pod annotations
podAnnotations:
  kubectl.kubernetes.io/default-container: manager

# Startup probe for slow-starting containers
startupProbe:
  enabled: true
  httpGet:
    path: /healthz
    port: 8081
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 30

# Probes with longer delays for testing
livenessProbe:
  enabled: true
  httpGet:
    path: /healthz
    port: 8081
  initialDelaySeconds: 120
  periodSeconds: 60
  timeoutSeconds: 30
  failureThreshold: 5

readinessProbe:
  enabled: true
  httpGet:
    path: /readyz
    port: 8081
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 15
  failureThreshold: 3

# Metrics
metrics:
  enabled: true
  serviceMonitor:
    enabled: false

# Test environment specific settings
env:
  - name: LOG_LEVEL
    value: "info"
  - name: LEADER_ELECT
    value: "false"  # Disable leader election for single replica testing
