apiVersion: v2
name: cronjob-scale-down-operator
description: >-
  A Kubernetes operator that automatically scales down Deployments and StatefulSets
  during specific time windows and provides comprehensive resource cleanup capabilities
type: application
version: 0.4.0
appVersion: "0.4.0"
keywords:
  - kubernetes
  - operator
  - scaling
  - cleanup
  - cron
  - cost-optimization
  - automation
  - scheduling
home: https://github.com/cronschedules/charts
sources:
  - https://github.com/cronschedules/charts
  - https://github.com/z4ck404/cronjob-scale-down-operator
maintainers:
  - name: z4ck404
    email: zakaria@elbazi.co
    url: https://github.com/z4ck404
icon: https://raw.githubusercontent.com/cronschedules/charts/main/cronjob-scale-down-operator/icon.png
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Deep Insights
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/category: monitoring-logging
  artifacthub.io/changes: |
    - kind: added
      description: Orphan resource cleanup functionality for cleaning up resources without cleanup annotations based on age thresholds
    - kind: added
      description: Extended resource type support including Pod, Job, Role, RoleBinding, ClusterRole, and ClusterRoleBinding for comprehensive cleanup
    - kind: added
      description: Enhanced RBAC permissions for new resource types to support extended cleanup capabilities
    - kind: improved
      description: Enhanced cleanup configuration with cleanupOrphanResources and orphanResourceMaxAge options for better resource management
    - kind: improved
      description: Updated operator to version 0.4.0 with comprehensive resource cleanup and orphan management features
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/cronschedules/charts/tree/main/cronjob-scale-down-operator
    - name: Operator Source
      url: https://github.com/z4ck404/cronjob-scale-down-operator
  artifacthub.io/install: |
    kubectl create namespace cronschedules-system
    helm install cronjob-scale-down-operator cronschedules/cronjob-scale-down-operator --namespace cronschedules-system
