apiVersion: v2
name: cronjob-scale-down-operator
description: >-
  A Kubernetes operator that automatically scales down Deployments and StatefulSets
  during specific time windows and provides comprehensive resource cleanup capabilities
type: application
version: 0.4.1
appVersion: "0.4.1"
keywords:
  - kubernetes
  - operator
  - scaling
  - cleanup
  - cron
  - cost-optimization
  - automation
  - scheduling
home: https://github.com/cronschedules/charts
sources:
  - https://github.com/cronschedules/charts
  - https://github.com/z4ck404/cronjob-scale-down-operator
maintainers:
  - name: z4ck404
    email: zakaria@elbazi.co
    url: https://github.com/z4ck404
icon: https://raw.githubusercontent.com/cronschedules/charts/main/cronjob-scale-down-operator/icon.png
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Deep Insights
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/category: monitoring-logging
  artifacthub.io/changes: |
    - kind: added
      description: Comprehensive Prometheus metrics support for monitoring and observability
    - kind: added
      description: Scale operation metrics with target resource details and reconciliation tracking
    - kind: added
      description: Resource cleanup metrics by type, label, and orphan resource tracking
    - kind: added
      description: Grafana dashboard example and PromQL queries documentation
    - kind: security
      description: Updated vulnerable dependencies including golang.org/x/oauth2 and golang.org/x/net
    - kind: security
      description: Updated Go version from 1.23.0 to 1.23.12 fixing CVE-2025-47907
    - kind: fixed
      description: Improved graceful handling of missing target resources with cleaner logging
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/cronschedules/charts/tree/main/cronjob-scale-down-operator
    - name: Operator Source
      url: https://github.com/z4ck404/cronjob-scale-down-operator
  artifacthub.io/install: |
    kubectl create namespace cronschedules-system
    helm install cronjob-scale-down-operator cronschedules/cronjob-scale-down-operator --namespace cronschedules-system
